# Generated by Django 5.2.6 on 2025-09-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_number',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Cart 1'), (2, 'Cart 2'), (3, 'Cart 3')], default=1),
        ),
    ]
